server:
  port : 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aawt7jx7g0mfr4.clv1iw1t9wfh.us-east-1.rds.amazonaws.com:3306/ebdb
    username: rootroot
    password: rootroot

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

logging:
  level:
    org:
      springframework:
        web: DEBUG

application:
  key: 1


